title: San Mu's blog
author: Marlowe
email: f1553466671@163.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is built to record some issue and experience about install software and use of software.
# social links
weibo: FMarlowe
github_username: f15534666671

show_excerpts: true # set to false to remove excerpts on the homepage


theme: jekyll-theme-cayman
